### PR TITLE
Changed ExtractContentType to use mime.ParseMediaType. Fixes #91.

### LINKED ISSUE #91: Content-Type header validation fails if the content type contains custom header values
A response with, for example, a `Content-Type: application/json; version=2` header fails validation against a spec that defines that same type as a valid response type, like so:
```
... path and operation omitted ...
"responses": {
  "200": {
    "content": {
      "application/json; version=2": {
        "schema": { ... }
      }
    }
  }
}
```

The returned validation error:
```
Message: GET / 200 operation response content type 'application/json' does not exist
HowToFix: The content type is invalid, Use one of the 1 supported types for this operation: application/json; version=2
```

This seems to be happening because [helpers.ExtractContentType()](https://github.com/pb33f/libopenapi-validator/blob/main/helpers/operation_utilities.go#L39) assumes `Charset` and `Boundary` as the only valid header values for `Content-Type` and discards everything else.

Further down the validation logic, on L72 of [responseBodyValidator.ValidateResponseBodyWithPathItem()](https://github.com/pb33f/libopenapi-validator/blob/main/responses/validate_body.go#L72), this content type stripped to a media type is then being compared directly with the content types allowed by the specification. This will of course always fail if any additional header values are present in the spec.

### PR DESCRIPTION
**Pull request by wizardishungry**

### CODE REVIEW

File: helpers/operation_utilities.go [hunk 1]
```diff
@@ -38,23 +38,8 @@ func ExtractOperation(request *http.Request, item *v3.PathItem) *v3.Operation {
...
-				}
-			}
-		}
-	} else {
-		contentType = strings.TrimSpace(contentType)
-	}
-	return contentType, charset, boundary
+	// mime.ParseMediaType: "If there is an error parsing the optional parameter,
+	// the media type will be returned along with the error ErrInvalidMediaParameter."
+	ct, params, _ := mime.ParseMediaType(contentType)
```
Comment (ccoVeille) [inline helpers/operation_utilities.go:43]: This comment help to understand why you are ignoring the possible error.

Please add a test about this

Comment (wizardishungry) [reply helpers/operation_utilities.go:43]: Done.

**Review by ccoVeille — APPROVED** [review]

**Review by daveshanley — APPROVED** [review]
Thank you for your contribution!
