### PR TITLE
fix: support for path validation for odata-formatted openapi specs

### LINKED ISSUE #126: OData formatted OpenAPI Spec validations not working
When attempting to validate an OData formatted OpenAPI specification using the libopenapi-validator library, the validation fails. The issue seems to be related to the handling of OData path parameters and their specific formatting.

### Steps to Reproduce:

1. Run the below program.
```go
package main

import (
	"fmt"
	"github.com/pb33f/libopenapi"
	validator "github.com/pb33f/libopenapi-validator"
	"net/http"
)

const openAPISpec = `{
  "openapi": "3.0.0",
  "info": {
    "title": "Sample OData Service",
    "version": "1.0.0"
  },
  "paths": {
    "/orders(OrderID='{OrderID}',OrderDate=datetime'{OrderDate}')": {
      "parameters": [
        {
          "name": "OrderID",
          "in": "path",
          "required": true,
          "schema": {
            "type": "integer",
            "format": "uint8",
          }
        },
        {
          "name": "OrderDate",
          "in": "path",
          "required": true,
          "schema": {
            "type": "string"
          }
        }
      ],
      "get": {
        "responses": {
          "200": {
            "description": "Retrieved entity"
          }
        }
      }
    }
  }
}`

func main() {

	document, err := libopenapi.NewDocument([]byte(openAPISpec))
	if err != nil {
		panic(err)
	}

	_, errs := document.BuildV3Model()
	if len(errs) != 0 {
		panic(errs[0])
	}

	libopenapiValidator, errs := validator.NewValidator(document)
	if len(errs) != 0 {
		panic(errs[0])
	}

	invalidPathReq, _ := http.NewRequest(http.MethodGet, "/invalid", nil)
	isSuccess, valErrs := libopenapiValidator.ValidateHttpRequest(invalidPathReq) // this should fail due to invalid path
	if !isSuccess {
		panic("Error in validating path: " + valErrs[0].Error())
	}
	fmt.Println("Path validation successful")

	invalidParameterReq, _ := http.NewRequest(http.MethodGet, "/orders(OrderID='abc',OrderDate=datetime'1492041600000')", nil)
	isSuccess, valErrs = libopenapiValidator.GetParameterValidator().ValidatePathParams(invalidParameterReq) // this should fail due to invalid parameter
	if !isSuccess {
		panic("Error in validating path: " + valErrs[0].Error())
	}
	fmt.Println("Parameter validation successful")
}
```

### Expected Behavior:
Both validations should fail.

### Actual Behavior:
The validations pass, indicating an issue with the handling of OData path and path parameters.

### Possible enhancements

- the function used to [compare paths](https://github.com/pb33f/libopenapi-validator/blob/main/paths/paths.go#L191-L206)
- the function used to [validate parameters](https://github.com/pb33f/libopenapi-validator/blob/main/parameters/path_parameters.go#L29-L297)

### PR DESCRIPTION
**Pull request by Rishabh-Daga**
fixes #126

### CODE REVIEW

**Comment by Rishabh-Daga** [comment]
@wizardishungry @arnaldur @k1LoW can you please take a look ? Thanks.

**Comment by daveshanley** [comment]
Can you bump coverage please?

**Comment by Rishabh-Daga** [comment]
Hi @daveshanley, did you get a chance to look at the PR ?

**Comment by Rishabh-Daga** [comment]
> Can you bump coverage please?

Done.

File: helpers/regex_maker.go [hunk 1]
```diff
@@ -0,0 +1,93 @@
+package helpers
+
+import (
+	"bytes"
+	"fmt"
+	"regexp"
+	"strings"
+)
+
+func GetRegexForPath(tpl string) (*regexp.Regexp, error) {
```
Comment (daveshanley) [inline helpers/regex_maker.go:10]: add go doc please

File: helpers/regex_maker.go [hunk 2]
```diff
@@ -0,0 +1,93 @@
...
+	// Check for capturing groups which used to work in older versions
+	if reg.NumSubexp() != len(idxs)/2 {
+		return nil, fmt.Errorf("route %s contains capture groups in its regexp. Only non-capturing groups are accepted: e.g. (?:pattern) instead of (pattern)", template)
+	}
+
+	// Done!
+	return reg, nil
+}
+
+func BraceIndices(s string) ([]int, error) {
```
Comment (daveshanley) [inline helpers/regex_maker.go:72]: go doc please

**Review by daveshanley — CHANGES_REQUESTED** [review]
LGTM, thanks, just a couple of docs to be added.

File: helpers/regex_maker.go (hunk 1 above)
Comment (Rishabh-Daga) [reply helpers/regex_maker.go:35]: done

File: helpers/regex_maker.go (hunk 2 above)
Comment (Rishabh-Daga) [reply helpers/regex_maker.go:118]: done

**Comment by Rishabh-Daga** [comment]
> LGTM, thanks, just a couple of docs to be added.

Added. Can you verify ? Thanks.

**Review by daveshanley — APPROVED** [review]
LGTM!
